version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      angular:
        patterns:
          - "@angular/*"
        update-types:
          - "minor"
          - "patch"
