# BUILD PROJECT ##
FROM node:14.15.1-alpine as build
ARG environment

WORKDIR /workspace/
ADD package.json /workspace/
RUN npm install

COPY . /workspace/
RUN $(npm bin)/ng build --configuration=$environment

# FOR RUNNING TESTS ##
# (copy dist build-files)
# copy working files and install dependecies and chrome for test run
FROM nginx:1.19.5-alpine AS runtime

RUN apk update
RUN apk add --update nodejs npm

# Installs latest Chromium package

#RUN  echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
#    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
#    apk add --no-cache bash chromium@edge nss@edge
RUN apk update && apk add --no-cache chromium \
    chromium-chromedriver

# This line is to tell karma-chrome-launcher where
# chromium was downloaded and installed to.
ENV CHROME_BIN /usr/bin/chromium-browser

COPY  --from=build /workspace/dist/ /usr/share/nginx/html/
COPY --from=build /workspace/ /spring-petclinic-angular/

RUN cd /spring-petclinic-angular/ && \
       npm install

EXPOSE 8080

